version: '3'

services:
    postgres:
        image: postgres:15.2-alpine3.17
        container_name: PlayerService_postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        networks:
            - player_service_network
        ports:
            - '5432:5432'
        volumes:
            - ./data/db:/var/lib/postgresql/data
        restart: on-failure
        healthcheck:
            test: [ 'CMD-SHELL', 'pg_isready' ]
            interval: 10s
            timeout: 5s
            retries: 5

    pgadmin:
        container_name: PlayerService_pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@playerservice.ru
            PGADMIN_DEFAULT_PASSWORD: admin
        networks:
            - player_service_network
        ports:
            - '8081:80'
        restart: on-failure

    player:
        build: .
        container_name: PlayerService
        networks:
            - player_service_network
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - '8080:8080'
        restart: on-failure

networks:
    player_service_network:
        driver: bridge
